CREATE ROLE blog_app LOGIN PASSWORD 'blog_app_test_only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
GRANT CONNECT ON DATABASE blog_test_migrations TO blog_app;
GRANT USAGE ON SCHEMA public TO blog_app;
